# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Starting with 7.x, Guice switches from javax.* to jakarta.* bindings.
      # See https://github.com/google/guice/wiki/Guice700
      - dependency-name: "com.google.inject:guice"
        versions: [">=7.0.0"]
      # Bad release in Artifactory breaks Dependabot
      - dependency-name: "com.sonyericsson.jenkins.plugins.bfa:build-failure-analyzer"
        versions: ["2.27.0"]
      # This is the minimum Jenkins version
      - dependency-name: "org.jenkins-ci.main:cli"
      # Restrict updates to Jetty in the 11.x space
      - dependency-name: "org.eclipse.jetty:*"
        versions: [">=12.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "build-monitor-plugin"
    schedule:
      interval: "weekly"
    ignore:
      # Breaking changes, see:
      # https://github.com/jenkinsci/build-monitor-plugin/pull/677
      - dependency-name: "jasmine-core"
        versions: [">=3.0.0"]
